### ISSUE TITLE
Astro SSR vue integration fails with "Missing "./server-renderer" specifier"

### ISSUE THREAD

**Issue by gkatsanos** [vitejs/vite-plugin-vue#157]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug
I am importing an (uncompiled) Vue component which lives in a separate repository / codebase. 

```js
import { defineConfig } from "astro/config";
import node from "@astrojs/node";
import vue from "@astrojs/vue";
import svgLoader from "vite-svg-loader";
import tailwind from "@astrojs/tailwind";

// https://astro.build/config
export default defineConfig({
  server: {
    port: 3000,
    host: "0.0.0.0",
  },
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
  build: {
    assets: "requests-frontend/_astro",
  },
  vite: {
    plugins: [
      svgLoader({
        defaultImport: "url", // or 'raw'
      }),
    ],
    ssr: {
      noExternal: ["path-to-regexp"],
      external: ["form-data", "axios"],
    },
    optimizeDeps: {
      // Why? dd-trace attempts to patch graphql, but it's not a dependency of this project.
      exclude: ["graphql"],
    },
  },
  integrations: [vue(), tailwind()],
});

```

```json
{
  "name": "request-frontend",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "start": "NODE_OPTIONS='-r dd-trace/init' HOST=0.0.0.0 PORT=3000 node ./dist/server/entry.mjs",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/node": "^5.1.1",
    "@astrojs/renderer-vue": "^0.4.0",
    "@astrojs/tailwind": "^3.1.1",
    "@astrojs/vue": "^2.1.1",
    "@visable-dev/routing": "^7.1.0",
    "@visable-dev/tracking": "^3.0.0",
    "@visable-dev/ui-components": "^0.8.1",
    "@visable-dev/vue": "^16.0.1",
    "@visable-dev/wlw-tailwindcss-config": "^3.0.11",
    "@vue/server-renderer": "^3.2.47",
    "astro": "^2.3.0",
    "dd-trace": "^3.17.1",
    "sass": "^1.62.0",
    "tailwindcss": "^3.3.1",
    "vue": "^3.2.47"
  },
  "engines": {
    "node": ">=16.16.0",
    "pnpm": ">=8",
    "sass": "^1.62.0"
  },
  "devDependencies": {
    "vite-svg-loader": "^4.0.0"
  }
}
```

```jsx
---
import VisPageHeader from '@visable-dev/vue/components/VisPageHeader/index.vue'
export interface Props {
	title: string;
}
const { title } = Astro.props;
const { lang } = Astro.params;

---

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>{title}</title>

	</head>
	<body>
		<VisPageHeader />
		<slot />
	</body>
</html>
```

running a vite build:

```
[commonjs--resolver] Missing "./server-renderer" specifier in "vue" package
 error   Missing "./server-renderer" specifier in "vue" package
  File:
    /Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:25
  Code:
    > 16638 | function e(e,n,r){throw new Error(r?`No known conditions for "${n}" specifier in "${e}" package`:`Missing "${n}" specifier in "${e}" package`)}function n(n,i,o,f){let s,u,l=r(n,o),c=function(e){let n=new Set(["default",...e.conditions||[]]);return e.unsafe||n.add(e.require?"require":"import"),e.unsafe||n.add(e.browser?"browser":"node"),n}(f||{}),a=i[l];if(void 0===a){let e,n,r,t;for(t in i)n&&t.length<n.length||("/"===t[t.length-1]&&l.startsWith(t)?(u=l.substring(t.length),n=t):t.length>1&&(r=t.indexOf("*",2),~r&&(e=RegExp("^"+t.substring(0,r)+"(.*)"+t.substring(1+r)).exec(l),e&&e[1]&&(u=e[1],n=t))));a=i[n];}return a||e(n,l),s=t(a,c),s||e(n,l,1),u&&function(e,n){let r,t=0,i=e.length,o=/[*]/g,f=/[/]$/;for(;t<i;t++)e[t]=o.test(r=e[t])?r.replace(o,n):f.test(r)?r+n:r;}(s,u),s}function r(e,n,r){if(e===n||"."===n)return ".";let t=e+"/",i=t.length,o=n.slice(0,i)===t,f=o?n.slice(i):n;return "#"===f[0]?f:o||!r?"./"===f.slice(0,2)?f:"./"+f:f}function t(e,n,r){if(e){if("string"==typeof e)return r&&r.add(e),[e];let i,o;if(Array.isArray(e)){for(o=r||new Set,i=0;i<e.length;i++)t(e[i],n,o);if(!r&&o.size)return [...o]}else for(i in e)if(n.has(i))return t(e[i],n,r)}}function o(e,r,t){let i,o=e.exports;if(o){if("string"==typeof o)o={".":o};else for(i in o){"."!==i[0]&&(o={".":o});break}return n(e.name,o,r||".",t)}}function f(e,r,t){if(e.imports)return n(e.name,e.imports,r,t)}
            |                         ^
      16640 | // This file was generated. Do not modify manually!
      16641 | var astralIdentifierCodes = [509, 0, 227, 0, 150, 4, 294, 9, 1368, 2, 2, 1, 6, 3, 41, 2, 5, 0, 166, 1, 574, 3, 9, 9, 370, 1, 81, 2, 71, 10, 50, 3, 123, 2, 54, 14, 32, 10, 3, 1, 11, 3, 46, 10, 8, 0, 46, 9, 7, 2, 37, 13, 2, 9, 6, 1, 45, 0, 13, 2, 49, 13, 9, 3, 2, 11, 83, 11, 7, 0, 3, 0, 158, 11, 6, 9, 7, 3, 56, 1, 2, 6, 3, 1, 3, 2, 10, 0, 11, 1, 3, 6, 4, 4, 193, 17, 10, 9, 5, 0, 82, 19, 13, 9, 214, 6, 3, 8, 28, 1, 83, 16, 16, 9, 82, 12, 9, 9, 84, 14, 5, 9, 243, 14, 166, 9, 71, 5, 2, 1, 3, 3, 2, 0, 2, 1, 13, 9, 120, 6, 3, 6, 4, 0, 29, 9, 41, 6, 2, 3, 9, 0, 10, 10, 47, 15, 406, 7, 2, 7, 17, 9, 57, 21, 2, 13, 123, 5, 4, 0, 2, 1, 2, 6, 2, 0, 9, 9, 49, 4, 2, 1, 2, 4, 9, 9, 330, 3, 10, 1, 2, 0, 49, 6, 4, 4, 14, 9, 5351, 0, 7, 14, 13835, 9, 87, 9, 39, 4, 60, 6, 26, 9, 1014, 0, 2, 54, 8, 3, 82, 0, 12, 1, 19628, 1, 4706, 45, 3, 22, 543, 4, 4, 5, 9, 7, 3, 6, 31, 3, 149, 2, 1418, 49, 513, 54, 5, 49, 9, 0, 15, 0, 23, 4, 2, 14, 1361, 6, 2, 16, 3, 6, 2, 1, 2, 4, 101, 0, 161, 6, 10, 9, 357, 0, 62, 13, 499, 13, 983, 6, 110, 6, 6, 9, 4759, 9, 787719, 239];
  Stacktrace:
Error: Missing "./server-renderer" specifier in "vue" package
    at e (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:25)
    at n (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:627)
    at o (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:1297)
    at resolveExportsOrImports (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23396:20)
    at resolveDeepImport (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23415:31)
    at tryNodeResolve (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23104:20)
    at Object.resolveId (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:22865:28)
    at Object.handler (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/vite@4.3.1_sass@1.62.0/node_modules/vite/dist/node/chunks/dep-24daf00c.js:46609:19)
    at file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/rollup@3.21.0/node_modules/rollup/dist/es/shared/node-entry.js:24526:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/rollup@3.21.0/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
```

tried everything, imported component is empty:
```html
// components/VisPageHeader/index.vue
<template>
  <header>aa</header>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'vis-page-header',
  setup() {
    return {}
  },
})
</script>




### Reproduction

https://stackblitz.com/edit/ssr-vue-astro-issue

### Steps to reproduce

https://stackblitz.com/edit/ssr-vue-astro-issue

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.14 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yyx990803** [comment]
I don't think this should be reported here, seems to belong to the Astro integration.

**Comment by gkatsanos** [comment]
@yyx990803 It seems that the astro plugin used to import Vue components is a layer on top of this vite plugin, but I may be wrong. https://www.npmjs.com/package/@astrojs/vue 

![image](https://user-images.githubusercontent.com/1768834/234229141-9560d552-bd88-49f7-92df-c6234c7ef4dc.png)

We're fighting with this for some weeks now, I'd be appreciative if we dont ping-pong it between repos :(
