### ISSUE TITLE
[vite:css-post] Plugin error - Unable to get file name for unknown file "2fa9c3fa".

### ISSUE THREAD

**Issue by gcq-z** [vitejs/vite-plugin-vue#174]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I use legacy on vite4.2.0+@ vitejs/plugin legacy4{

targets: ['chrome 58']

}Error reported during rendering chunks

### Reproduction

not have

### Steps to reproduce

Run 'npm run build'
:[vite:css-post] Plugin error - Unable to get file name for unknown file "2fa9c3fa".
✓ built in 7.80s
error during build:
RollupError: Plugin error - Unable to get file name for unknown file "2fa9c3fa".
    at error (file:///vite-project-platform/node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
    at Object.FileEmitter.getFileName (file:///vite-project-platform/node_modules/rollup/dist/es/shared/node-entry.js:23972:24)
    at file:///vite-project-platform/node_modules/vite/dist/node/chunks/dep-79892de8.js:38026:43
    at String.replace (<anonymous>)
    at resolveAssetUrlsInCss (file:///vite-project-platform/node_modules/vite/dist/node/chunks/dep-79892de8.js:38025:37)
    at Object.renderChunk (fvite-project-platform/node_modules/vite/dist/node/chunks/dep-79892de8.js:38054:32)
    at file:///vite-project-platform/node_modules/rollup/dist/es/shared/node-entry.js:24395:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 2.45 GB / 15.37 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-legacy: ^4.0.2 => 4.0.2
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0
    vite: ^4.2.0 => 4.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gcq-z** [comment]
import { defineConfig } from 'vite'
import path from 'path'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import VueComponents from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
import { VantResolver } from 'unplugin-vue-components/resolvers'
import UNO_CSS from 'unocss/vite'
import legacy from '@vitejs/plugin-legacy'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    // 设置src别名
    alias: {
      '@': path.resolve(__dirname, 'src')
    }
  },
  plugins: [
    vue(),
    AutoImport({
      imports: ['vue', 'vue-router'],
      resolvers: [ElementPlusResolver()],
      dts: 'src/auto-import.d.ts'
    }),
    VueComponents({
      dts: 'src/components.d.ts',
      resolvers: [ElementPlusResolver(), VantResolver()]
    }),
    UNO_CSS(),
    legacy({
      targets: ['chrome 58']
    })
  ],
  publicDir: 'public',
  base: './',
  build: {
    // target:['chrome 58'],
    rollupOptions: {
      output: {
        chunkFileNames: 'js/[name]-[hash].js',
        entryFileNames: 'js/[name]-[hash].js',
        assetFileNames: '[ext]/[name]-[hash].[ext]'
      }
    }
  }
})
