### ISSUE TITLE
[plugin vite:dep-pre-bundle] Failed to resolve entry for package "form-data". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by ArkURL** [vitejs/vite-plugin-vue#67]
### Related plugins

- [x] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I was trying to import axios service in Vite + Vue3 project and configurate all files. But an error occurred when I typed "yarn dev" to start the server.
I was totally use the package below:
element-plus

- axios

- vue-router@4

- postcss-px-to-viewport

- postcss-nested

The error messsage below:
```bash
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1355:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "form-data". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1594:15)
    at F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1050:28
    at runOnEndCallbacks (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1466:61)
    at buildResponseToResult (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1048:7)
    at F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1160:14
    at responseCallbacks.<computed> (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "form-data". The package may have incorrect main/module/exports specified in its package.json.
          at packageEntryFailure (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22973:11)
          at resolvePackageEntry (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22970:5)
          at tryNodeResolve (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22708:20)
          at Context.resolveId (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22472:28)
          at Object.resolveId (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:42553:46)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:62762:21
          at async file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:23290:34
          at async requestCallbacks.on-resolve (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:1355:22)
          at async handleRequest (F:\web\vue-project\web-notes\node_modules\esbuild\lib\main.js:723:13),
      id: '',
      location: {
        column: 21,
        file: 'node_modules/esbuild/lib/main.js',
        length: 0,
        line: 1355,
        lineText: '        let result = await callback({\n' +
          '    at packageEntryFailure (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22973:11)\n' +
          '    at resolvePackageEntry (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22970:5)\n' +
          '    at tryNodeResolve (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22708:20)\n' +
          '    at Context.resolveId (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:22472:28)\n' +
          '    at Object.resolveId (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:42553:46)\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:62762:21\n' +
          '    at async file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:23290:34\n' +
          '    at async requestCallbacks.on-resolve (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:1355:22)\n' +
          '    at async handleRequest (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:723:13)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1279,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:23270:19)\n' +
              '    at handlePlugins (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:1279:21)\n' +
              '    at buildOrServeImpl (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:968:5)\n' +
              '    at Object.buildOrServe (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:776:5)\n' +
              '    at F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:2115:17\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.build (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:2114:14)\n' +
              '    at build (F:\\web\\vue-project\\web-notes\\node_modules\\esbuild\\lib\\main.js:1961:51)\n' +
              '    at runOptimizeDeps (file:///F:/web/vue-project/web-notes/node_modules/vite/dist/node/chunks/dep-6305614c.js:43909:26)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 21,
            file: 'node_modules/axios/lib/env/classes/FormData.js',
            length: 11,
            line: 1,
            lineText: "import FormData from 'form-data';",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "form-data". The package may have incorrect main/module/exports specified in its package.json.'      
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
And my vite.config.ts file as below:
```ts
import { defineConfig, loadEnv } from "vite";
import vue from "@vitejs/plugin-vue";
import { resolve } from "path";
import AutoImport from "unplugin-auto-import/vite";
import Components from "unplugin-vue-components/vite";
import PostCSSNested from "postcss-nested";
import PostCSSPxToViewport from "postcss-px-to-viewport";
import { ElementPlusResolver } from "unplugin-vue-components/resolvers";

https://vitejs.dev/config/
export default ({ mode }) => {
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) };
  return defineConfig({
    plugins: [
      vue(),
      AutoImport({ resolvers: [ElementPlusResolver()] }),
      Components({ resolvers: [ElementPlusResolver()] }),
    ],
    server: {
      proxy: {
        "/api": {
          target: 'http://localhost:9000',
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
    resolve: {
      alias: {
        "@": resolve(__dirname, "./src"),
      },
      extensions: [".ts"],
    },
    css: {
      postcss: {
        plugins: [
          PostCSSNested,
          PostCSSPxToViewport({
            unitToConvert: "px",
            viewportWidth: 1920,
            unitPrecision: 5,
            propList: ["*"],
            viewportUnit: "vw",
            fontViewportUnit: "vw",
            selectorBlackList: [],
            minPixelValue: 1,
            mediaQuery: false,
            replace: true,
            exclude: undefined,
            include: undefined,
            landscape: false,
            landscapeUnit: "vw",
            landscapeWidth: 568,
          }),
        ],
      },
    },
  });
};
```
package.json file below:
```json
{
  "name": "web-notes",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "axios": "^1.2.1",
    "element-plus": "^2.2.27",
    "vue": "^3.2.45",
    "vue-router": "4"
  },
  "devDependencies": {
    "@types/node": "^18.11.17",
    "@vitejs/plugin-vue": "^4.0.0",
    "postcss-nested": "^6.0.0",
    "postcss-px-to-viewport": "^1.1.1",
    "typescript": "^4.9.3",
    "unplugin-auto-import": "^0.12.1",
    "unplugin-vue-components": "^0.22.12",
    "vite": "^4.0.0",
    "vue-tsc": "^1.0.11"
  }
}

```

### Reproduction

https://github.com/ArkURL/vitejs-vite-hr89tb

### Steps to reproduce

Run bash script as below:
yarn create vite
...
$ yarn add element-plus
$ yarn add -D unplugin-vue-components unplugin-auto-import
$ yarn add postcss-px-to-viewport postcss-nested -D
$ yarn add @types/node -D
then edit vite.config.ts file content as below:
```ts
import { defineConfig, loadEnv } from "vite";
import vue from "@vitejs/plugin-vue";
import { resolve } from "path";
import AutoImport from "unplugin-auto-import/vite";
import Components from "unplugin-vue-components/vite";
import PostCSSNested from "postcss-nested";
import PostCSSPxToViewport from "postcss-px-to-viewport";
import { ElementPlusResolver } from "unplugin-vue-components/resolvers";

export default defineConfig({
  plugins: [
    vue(),
    AutoImport({ resolvers: [ElementPlusResolver()] }),
    Components({ resolvers: [ElementPlusResolver()] }),
  ],
  server: {
    proxy: {
      "/api": {
        target: "http://localhost:9000",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ""),
      },
    },
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "./src"),
    },
    extensions: [".ts"],
  },
  css: {
    postcss: {
      plugins: [
        PostCSSNested,
        PostCSSPxToViewport({
          unitToConvert: "px",
          viewportWidth: 1920,
          unitPrecision: 5,
          propList: ["*"],
          viewportUnit: "vw",
          fontViewportUnit: "vw",
          selectorBlackList: [],
          minPixelValue: 1,
          mediaQuery: false,
          replace: true,
          exclude: undefined,
          include: undefined,
          landscape: false,
          landscapeUnit: "vw",
          landscapeWidth: 568,
        }),
      ],
    },
  },
});
```
and then create axios.ts file to use as below:
```ts
import axios from 'axios'
import type {AxiosRequestConfig, AxiosError, AxiosResponse} from 'axios'

const axiosInstance = axios.create({
    baseURL: '',
    timeout: 2000
})

axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
    return config
}, (error: AxiosError) => {
    return Promise.reject(error)
})

axiosInstance.interceptors.response.use((response: AxiosResponse) => {
    return response
}, (error: AxiosError) => {
    return Promise.reject(error)
})

export default axiosInstance
```
and then import axios in vue component.Then the problem occurred.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz     
    Memory: 6.13 GB / 15.96 GB
  Binaries:
    Node: 16.16.0 - D:\program\node\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - D:\program\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    vite: ^4.0.0 => 4.0.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArkURL** [comment]
I compare the project work well which I uploaded and the project with problem locally, I found that the project uploaded in stackblitz.com was automatically added `vite.config.js` file and that make the project work well!
I don't know why this happened.
The `vite.config.js` file which was automatically added content below:
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
})
```

**Comment by ArkURL** [comment]
> I compare the project work well which I uploaded and the project with problem locally, I found that the project uploaded in stackblitz.com was automatically added `vite.config.js` file and that make the project work well! I don't know why this happened. The `vite.config.js` file which was automatically added content below:
> 
> ```js
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [vue()],
> })
> ```

When I restart the project I found every config which was originally in `vite.config.ts` was not used. 🤣 So I guess Vite use `vite.config.js` instead of `vite.config.ts` when both exists.
So the problem had not resolve.

**Comment by ArkURL** [comment]
Problem resovled!
comment the code in `vite.config.ts` options.resolve.extensions can resolve the problem.
