### ISSUE TITLE
At least one <template> or <script> is required in a single file component

### ISSUE THREAD

**Issue by halilyuce** [vitejs/vite-plugin-vue#74]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I'm using this package for vitest tests. I ran into this problem after I did 'yarn upgrade' yesterday and I checked all packages and plugins one by one, that's the problem. When I remove the vue plugin from the Vite plugins config, it fixes itself, but when I add it back, I get this error.

`[plugin:vite:vue] At least one <template> or <script> is required in a single file component.`

vite.config.ts

```
import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [
    vue(),
  ],
  test: {
    include: ["tests/*.test.ts"],
  },
});
```

### Reproduction

it's a prod project

### Steps to reproduce

Run 'yarn' to install dependencies then 'yarn dev' to build the development environment.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) x64 Apple M1 Max
    Memory: 1.98 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
```

### Used Package Manager

yarn

### Logs

```
[vite] Internal server error: At least one <template> or <script> is required in a single file component.                 20:22:12
  Plugin: vite:vue
  File: /Users/yuce/Documents/portal/pages/index.vue
      at Object.parse (/Users/yuce/Documents/portal/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5245:21)
      at createDescriptor (file:///Users/yuce/Documents/portal/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
      at transformMain (file:///Users/yuce/Documents/portal/node_modules/@vitejs/plugin-vue/dist/index.mjs:2206:34)
      at TransformContext.transform (file:///Users/yuce/Documents/portal/node_modules/@vitejs/plugin-vue/dist/index.mjs:2698:16)
      at Object.transform (file:///Users/yuce/Documents/portal/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41480:44)
      at async loadAndTransform (file:///Users/yuce/Documents/portal/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39287:29)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by halilyuce** [comment]
This is the solution that worked for me and here it is for those who are faced with the same issue:

```
plugins: [
    {
      ...vue(),
      apply: (config) => {
        return config.mode === "test";
      },
    },
]
```
